/*
 * Copyright (c) 2009-2015, Argon Sun (Fluorohydride)
 * Copyright (c) 2017-2025, Edoardo Lolletti (edo9300) <edoardo762@gmail.com>
 *
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */
#ifndef COMMON_H_
#define COMMON_H_

#if defined( _MSC_VER) && !defined(__clang_analyzer__)
#pragma warning(disable: 4244)
#define unreachable() __assume(0)
#define NoInline __declspec(noinline)
#define ForceInline __forceinline
#define Assume(cond) __assume(cond)
#else
#if !defined(__forceinline)
#define ForceInline __attribute__((always_inline)) inline
#else
#define ForceInline __forceinline
#endif
#define unreachable() __builtin_unreachable()
#define NoInline __attribute__ ((noinline))
#define Assume(cond) do { if(!(cond)){ unreachable(); } } while(0)
#endif

#if defined(__clang_analyzer__)
#undef NDEBUG
#endif

#include <cassert>
#include <cstdint>
#include "ocgapi_constants.h"

#define TRUE 1
#define FALSE 0

//Symbolic locations
#define LOCATION_FZONE   0x100
#define LOCATION_PZONE   0x200
#define LOCATION_STZONE  0x400
#define LOCATION_MMZONE  0x800
#define LOCATION_EMZONE  0x1000
//Locations redirect
#define LOCATION_DECKBOT	0x10001		//Return to deck bottom
#define LOCATION_DECKSHF	0x20001		//Return to deck and shuffle
#define LOCATION_REMOVED_FACEDOWN	0x10020

//
#define COIN_HEADS  1
#define COIN_TAILS  0

//Flip effect flags
#define NO_FLIP_EFFECT     0x10000

//Players
#define PLAYER_SELFDES  5

//Phases
#define PHASE_DRAW          0x01
#define PHASE_STANDBY       0x02
#define PHASE_MAIN1         0x04
#define PHASE_BATTLE_START  0x08
#define PHASE_BATTLE_STEP   0x10
#define PHASE_DAMAGE        0x20
#define PHASE_DAMAGE_CAL    0x40
#define PHASE_BATTLE        0x80
#define PHASE_MAIN2         0x100
#define PHASE_END           0x200

//Options
#define DUEL_TEST_MODE         0x01
#define DUEL_ATTACK_FIRST_TURN 0x02
#define DUEL_USE_TRAPS_IN_NEW_CHAIN 0x04
#define DUEL_6_STEP_BATLLE_STEP 0x08
#define DUEL_PSEUDO_SHUFFLE    0x10
#define DUEL_TRIGGER_WHEN_PRIVATE_KNOWLEDGE 0x20
#define DUEL_SIMPLE_AI         0x40
#define DUEL_RELAY             0x80
#define DUEL_OCG_OBSOLETE_IGNITION 0x100
#define DUEL_1ST_TURN_DRAW     0x200
#define DUEL_1_FACEUP_FIELD    0x400
#define DUEL_PZONE             0x800
#define DUEL_SEPARATE_PZONE    0x1000
#define DUEL_EMZONE            0x2000
#define DUEL_FSX_MMZONE        0x4000
#define DUEL_TRAP_MONSTERS_NOT_USE_ZONE    0x8000
#define DUEL_RETURN_TO_DECK_TRIGGERS 0x10000
#define DUEL_TRIGGER_ONLY_IN_LOCATION      0x20000
#define DUEL_SPSUMMON_ONCE_OLD_NEGATE      0x40000
#define DUEL_CANNOT_SUMMON_OATH_OLD        0x80000
#define DUEL_NO_STANDBY_PHASE  0x100000
#define DUEL_NO_MAIN_PHASE_2   0x200000
#define DUEL_3_COLUMNS_FIELD   0x400000
#define DUEL_DRAW_UNTIL_5      0x800000
#define DUEL_NO_HAND_LIMIT     0x1000000
#define DUEL_UNLIMITED_SUMMONS 0x2000000
#define DUEL_INVERTED_QUICK_PRIORITY       0x4000000
#define DUEL_EQUIP_NOT_SENT_IF_MISSING_TARGET       0x8000000
#define DUEL_0_ATK_DESTROYED   0x10000000
#define DUEL_STORE_ATTACK_REPLAYS   0x20000000
#define DUEL_SINGLE_CHAIN_IN_DAMAGE_SUBSTEP   0x40000000
#define DUEL_CAN_REPOS_IF_NON_SUMPLAYER 0x80000000
#define DUEL_TCG_SEGOC_NONPUBLIC	   0x100000000
#define DUEL_TCG_SEGOC_FIRSTTRIGGER 0x200000000
#define DUEL_TCG_FAST_EFFECT_IGNITION 0x400000000
#define DUEL_EXTRA_DECK_RITUAL 0x800000000
#define DUEL_NORMAL_SUMMON_FACEUP_DEF 0x1000000000
#define DUEL_PLAYING_CARDS		0x4000000000000000
#define DUEL_MODE_SPEED        (DUEL_3_COLUMNS_FIELD | DUEL_NO_MAIN_PHASE_2 | DUEL_TRAP_MONSTERS_NOT_USE_ZONE | DUEL_TRIGGER_ONLY_IN_LOCATION)
#define DUEL_MODE_RUSH         (DUEL_3_COLUMNS_FIELD | DUEL_NO_MAIN_PHASE_2 | DUEL_NO_STANDBY_PHASE | DUEL_1ST_TURN_DRAW | DUEL_INVERTED_QUICK_PRIORITY | DUEL_DRAW_UNTIL_5 | DUEL_NO_HAND_LIMIT | DUEL_UNLIMITED_SUMMONS | DUEL_TRAP_MONSTERS_NOT_USE_ZONE | DUEL_TRIGGER_ONLY_IN_LOCATION | DUEL_EXTRA_DECK_RITUAL)
#define DUEL_MODE_MR1          (DUEL_OCG_OBSOLETE_IGNITION | DUEL_1ST_TURN_DRAW | DUEL_1_FACEUP_FIELD | DUEL_SPSUMMON_ONCE_OLD_NEGATE | DUEL_RETURN_TO_DECK_TRIGGERS | DUEL_CANNOT_SUMMON_OATH_OLD)
#define DUEL_MODE_GOAT         (DUEL_MODE_MR1 | DUEL_TCG_FAST_EFFECT_IGNITION | DUEL_USE_TRAPS_IN_NEW_CHAIN | DUEL_6_STEP_BATLLE_STEP | DUEL_TRIGGER_WHEN_PRIVATE_KNOWLEDGE | DUEL_EQUIP_NOT_SENT_IF_MISSING_TARGET | DUEL_0_ATK_DESTROYED | DUEL_STORE_ATTACK_REPLAYS | DUEL_SINGLE_CHAIN_IN_DAMAGE_SUBSTEP | DUEL_CAN_REPOS_IF_NON_SUMPLAYER | DUEL_TCG_SEGOC_NONPUBLIC | DUEL_TCG_SEGOC_FIRSTTRIGGER)
#define DUEL_MODE_MR2          (DUEL_1ST_TURN_DRAW | DUEL_1_FACEUP_FIELD | DUEL_SPSUMMON_ONCE_OLD_NEGATE | DUEL_RETURN_TO_DECK_TRIGGERS | DUEL_CANNOT_SUMMON_OATH_OLD)
#define DUEL_MODE_MR3          (DUEL_PZONE | DUEL_SEPARATE_PZONE | DUEL_SPSUMMON_ONCE_OLD_NEGATE | DUEL_RETURN_TO_DECK_TRIGGERS | DUEL_CANNOT_SUMMON_OATH_OLD)
#define DUEL_MODE_MR4          (DUEL_PZONE | DUEL_EMZONE | DUEL_SPSUMMON_ONCE_OLD_NEGATE | DUEL_RETURN_TO_DECK_TRIGGERS | DUEL_CANNOT_SUMMON_OATH_OLD)
#define DUEL_MODE_MR5          (DUEL_PZONE | DUEL_EMZONE | DUEL_FSX_MMZONE | DUEL_TRAP_MONSTERS_NOT_USE_ZONE | DUEL_TRIGGER_ONLY_IN_LOCATION)
#define DUEL_MODE_PLAYING	   (DUEL_MODE_MR5 | DUEL_PLAYING_CARDS)
#define DUEL_MODE_MR1_FORB     (TYPE_XYZ | TYPE_PENDULUM | TYPE_LINK)
#define DUEL_MODE_MR2_FORB     (TYPE_PENDULUM | TYPE_LINK)
#define DUEL_MODE_MR3_FORB     TYPE_LINK
#define DUEL_MODE_MR4_FORB     0
#define DUEL_MODE_MR5_FORB     0


enum ActivityType : uint8_t {
	ACTIVITY_SUMMON = 1,
	ACTIVITY_NORMALSUMMON = 2,
	ACTIVITY_SPSUMMON = 3,
	ACTIVITY_FLIPSUMMON = 4,
	ACTIVITY_ATTACK = 5,
	ACTIVITY_BATTLE_PHASE = 6,
	ACTIVITY_CHAIN = 7,
};


#endif /* COMMON_H_ */
